targets:
  $default:
    builders:
      flutter_router|route_builder:
        enabled: true
      flutter_router|route_autowired_builder:
        enabled: true
builders:
  route_builder:
    import: 'package:flutter_router_generator/route_meta_generator.dart'
    builder_factories: ['routeBuilder']
    build_extensions: {'.dart': ['route.g.dart']}
    auto_apply: dependents
    runs_before: ['flutter_router_generator|route_autowired_builder']
    build_to: source
  route_autowired_builder:
    import: 'package:flutter_router_generator/route_meta_generator.dart'
    builder_factories: [ 'routeAutoWiredBuilder' ]
    build_extensions: { '.dart': [ 'routes.g.dart' ] }
    auto_apply: dependents
    build_to: source